<a href="https://colab.research.google.com/github/Siva-selvam/tensorflow/blob/main/02_tensor_randomgenerator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Random generator

In [2]:
import tensorflow as tf

In [5]:
#create two random tensors of same values
random_1 = tf.random.Generator.from_seed(11)   #set seed for the reproduceability of the same
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(11)
random_2 = random_2.normal(shape=(3,2))

In [6]:
#checking if both are equal
random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## Shuffle the tensors

In [12]:
tensor1 = tf.constant([[4,5],[6,7],[3,1],[1,1]])
tf.random.shuffle(tensor1)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[6, 7],
       [1, 1],
       [4, 5],
       [3, 1]], dtype=int32)>

In [26]:
tf.random.set_seed(11) #global seed
tf.random.shuffle(tensor1,seed=11) #operational seed - both must be set orelse it will take as random seed

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 1],
       [4, 5],
       [6, 7],
       [3, 1]], dtype=int32)>