<a href="https://colab.research.google.com/github/Siva-selvam/tensorflow/blob/main/03_tensors_from_np.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# converting numpy to tensors

In [1]:
import tensorflow as tf
import numpy as np

In [3]:
numpy = np.arange(1,25)
numpy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

#Ones and zeros

In [5]:
ones = tf.ones([3,4])
zeros = tf.zeros(shape=(4,5))
ones
zeros

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

#converting numpy aray to tensor

In [10]:
tens = tf.constant(numpy,shape=(3,8))
tens1 = tf.constant(numpy)
tens2 = tf.constant(numpy,shape=(2, 3, 4))
tens, tens1, tens2
# total we have 24 elements, so 2 * 3 * 4 = 24 or 3 * 4

(<tf.Tensor: shape=(3, 8), dtype=int64, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]])>,
 <tf.Tensor: shape=(24,), dtype=int64, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>)